Added the best projects from the previous year, as well as links to them
fmipython/PythonCourse2023 pull request #2
Opened 2023-09-29 09:03 UTC by lyubolp

2023-09-30 17:59 UTC, yalishanda42 commented
Ще е удобно и да включим този файл като страничка в Jupyterbook-a също, в раздела с проектите

2023-09-30 18:00 UTC, yalishanda42 requested changes

2023-09-30 18:00 UTC, yalishanda42 commented on example_projects.md
> +- [Schule, 2022/2023](https://github.com/karinaghristova/Schule)
Бих добавил Scribble и Gerrigram

Освен това ще е полезно да ги разделим по категории:

```suggestion
## Конзолни приложения / библиотеки
- [Password manager, 2022/2023](https://github.com/lyudmilstamenov/password_manager)
- [Poker API, 2022/2023](https://github.com/rosenkolev1/Python-Project)

## Desktop приложения / библиотеки
- [Pytomation, 2022/2023](https://github.com/kristian3551/Pytomaton)
- [Prolog interpreter, 2022/2023](https://github.com/HeavyHelium/python-course-project)

## Уебсайтове

- с Flask:
    - [Instagram clone, 2022/2023](https://github.com/GerganaAngelova02/Instagram_clone_app)

- с Django:
    - [Schule (електронен дневник), 2022/2023](https://github.com/karinaghristova/Schule)
    - [Scribble, 2022/2023](https://github.com/arctfx/scribble)

## Игри:
- [My-Bad-Bad-Ice-Cream, 2022/2023](https://github.com/YoanaAneva/My-Bad-Bad-Ice-Cream)
- [Triviador clone, 2022/2023](https://github.com/vladi2703/triviador-clone)
- [CubeMatic, 2022/2023](https://github.com/RylaD303/CubeMatic)
- [Minesweeper, 2022/2023](https://github.com/toduko/minesweeper)
```

2023-10-01 12:49 UTC, karinaghristova approved these changes

2023-10-01 17:32 UTC, merged