Lab 01
fmipython/PythonCourse2023 pull request #3
Opened 2023-10-20 15:43 UTC by yalishanda42

2023-10-20 16:03 UTC, karinaghristova requested changes
The following things need to be changed:
• Task 2: 
- Add def format_date_components(...) in the code cell
- Add the missing word/Fix spelling error for "цифрите на месеца и деня ДА точно 2"
• Task 3
- Change points in the message after the assert statements
• Task 6 
- Fix spelling error in "Лошите думички СЕ дадени"
• Proposal for grammatical correction in task 9
- Fix message after the assert statements to say 1 point instead of 1 points

2023-10-21 15:31 UTC, yalishanda42 commented
> The following things need to be changed:
> 
> * Task 2:
>   • Add def format_date_components(...) in the code cell
>   • Add the missing word/Fix spelling error for "цифрите на месеца и деня ДА точно 2"
> * Task 3
>   • Change points in the message after the assert statements
> * Task 6
>   • Fix spelling error in "Лошите думички СЕ дадени"
> * Proposal for grammatical correction in task 9
>   • Fix message after the assert statements to say 1 point instead of 1 points

thx, оправих всичко, само първото нарочно съм го оставил така, за да напишат сами и сигнатурата на функцията

2023-10-21 19:29 UTC, lyubolp approved these changes

2023-10-22 13:49 UTC, karinaghristova approved these changes

2023-10-22 16:24 UTC, merged